### ISSUE TITLE
Migrate from Win to Linux - Path hasn't changed correctly

### ISSUE THREAD

**Issue by gr1ffo** [Notifiarr/toolbarr#177]
I'm guessing I messed up here. I've tried to amend the path on my Sonarr db file and it doesn't seem to have worked correctly. I followed the walkthrough on the Wiki page.

Original Path: D:\Media\TV Series
New Path: /mnt/nas/TV Series

Path as displayed in Sonarr after restoring the db: /mnt/nas/TV Series/D:\Media\TV Series\

I've tried amending the path again but it doesn't remove the D:\ path.

**Comment by gr1ffo** [comment]
I tried again, in a different order, with better success. I had multiple original paths that I have combined into a single new path. In the first instance, I deleted the paths and then re-added the files to the new path, causing the above issue.

On my second attempt, first, I changed the paths to all records to new linux paths (/mnt/nas/TV Series/, ../TV Series1/ etc), and then deleted the paths to the placeholders (../TV Series1,2,3 etc) and added them to the proper path (../TV Series). This seems to have worked.

I'll try again with Radarr and see how I go.

Thanks very much for this Tool.

**Comment by davidnewhall** [comment]
Hello and thank you for opening an issue! The bug with Windows paths migration has been fixed. I cut a new release with the fix, so please [download the new version](https://github.com/Notifiarr/toolbarr/releases) and try that again.

**Comment by gr1ffo** [comment]
Thanks David!

I've downloaded the new .zip file. I can now delete instances, but this requires a restart after each time to make it responsive again. I can load a new db in the Radarr option however, it won't let me select either the 'Actions' or 'DB Tools' tab after its saved.

I haven't entered an URL or any other information. I've just uploaded the db.

**Comment by davidnewhall** [comment]
This sounds very strange. I'm on a Mac and I'm not able to reproduce this behavior you've described using version 0.1.2.

Try putting a Url and API key? it should work without them but may work better with them. Not real sure.

**Comment by gr1ffo** [comment]
I've tried using the URL and API key and still have the same result. To confirm, I'm not using the installer, just the amd64 zip.

Where is the config file stored? Maybe this is corrupt on mine and I need to erase it. I've been jumping between 0.1.1 and 0.1.2 to keep working on it. 0.1.1 has some bugs like not being able to delete a Sonarr or Radarr instance and some other minor things but I can make it work. On 0.1.2 I can delete a Sonarr or Radarr instance (with a restart) and load a db but I can't select another tab or add another instance.

**Comment by gr1ffo** [comment]
> There should also be a log file in the .toolbarr directory in your User folder. C:\Users\you\.toolbarr

Sorry just read this. I'll have a look and get back to you.

**Comment by davidnewhall** [comment]
I made a [few small changes](https://github.com/Notifiarr/toolbarr/pull/178). Would you mind grabbing another copy [from here](https://unstable.golift.io/toolbarr) and checking to see if it works any better?

**Comment by gr1ffo** [comment]
Seems to have the same issue. I tested under the Radarr tab.

I deleted the existing instance. I had to restart to get the app to respond again. Then I added back a db file. It appears to save successfully but the only 2 buttons are the 'Save' and 'Test' buttons and the 'Actions' and 'DB Tools' tabs don't open when selected. After restarting, the 'Reset' and 'Delete' buttons have appeared and a new window below the existing instance has appeared, 'Add New Radar Instance' however, selecting it doesn't do anything. The 'Actions' and 'DB Tools' tabs still don't open.

**Comment by nalllen** [comment]
Tired re installing it but still the same experience as gr1ffo have in the comment above, tried the one with the changes too but it behaves the same.

**Comment by davidnewhall** [comment]
@gr1ffo @nalllen -
Thank you for your patience while I work on this, and thank you for testing for me. I believe I've located the problem. Please download another copy [from here](https://unstable.golift.io/toolbarr) and let me know how it works out.
